PersonalWebsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^aboutMe/', include('aboutMe.urls')),
]

aboutMe/urls.py
from django.conf.urls import url
from . import views

app_name = 'aboutMe'

urlpatterns = [


    url(r'^$', views.index, name='index'),

    url(r'^resume/$', views.resume, name='resume'),


]

aboutMe/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

aboutMe/views.py
from django.http import HttpResponse
from django.template import loader

# Create your views here.


def index(request):
    template = loader.get_template('aboutMe/index.html')
    return HttpResponse(template.render(request))


def resume(request):
    template = loader.get_template('aboutMe/resume.html')
    return HttpResponse(template.render(request))

aboutMe/templates/aboutMe/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Derrick Adjie{% endblock %}</title>
    <!-- Loads the path to your static files-->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" type="test/css" href=" {% static 'aboutMe/styles.css' %}"/>
    <link href='https://fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>


<body>
<header><div class="icon"></div> </header>
<nav class="navbar navbar-default">
    <div class="container_fluid">

        <!-- Header-->
        <div class=" navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a class="nav-link" href="{% url 'aboutMe:index' %}">&nbsp;About Me</a></li>
                <li><a class="nav-link" href="{% url 'aboutMe:resume' %}">&nbsp;Resume</a></li>
            </ul>
        </div>
    </div>
</nav>

{% block body %}
{% endblock %}

<footer class="footer">
    <p>&copy; 2015 - <a href="#">Derrick Adjie</a></p>
</footer>
</body>
</html>

aboutMe/templates/aboutMe/index.html
{% extends 'aboutMe/base.html' %}


{% block body %} <!-- extends to the index page-->
<!-- <script type="text/paperscript" canvas="london-canvas" src="/js/animations.js"></script> -->

    <section class="jumbotron">
        <div class="image"></div>
        <div class="large-title-block">
            <h1><span class="large-title-block__start xxlarge">Hi,</span>
                <span class="large-title-block__middle xxlarge"> I'm </span>
                <span class="large-title-block__end xxlarge">Derrick Adjie.</span>
            </h1>

            <p class="home__subtitle">I'm a Web Developer based in London.</p>
        </div>

    </section>

    <div class="text-container">
        <div class="row">
            <div class="col-sm-12">
                <p>
                    I enjoy developing and designing websites, but I’m also passionate about all aspect of software
                    development and technology. I code in Python, HTML, CSS and Javascript. I’ve also worked with PHP
                    and Java. I’m proficient with Django and understand the MVC methodology. I really just enjoy
                    learning and working with some of the best current web frameworks such as bootstrap, SASS and LESS.
                    I believe I am a problem solver and enjoy having new challenges, puzzles to solve and being able to
                    think Logically during each stage of development.

                </p>
            </div>
        </div>
    </div>

{% endblock %}


<!--
variables go in the double squiggly lines.
python code goes in the squiggly braces and percent sign
-->

aboutMe/templates/aboutMe/resume.html
{% extends 'aboutMe/base.html' %}


<title>{% block title %} Resume {% endblock %}</title>


{% block body %}

    <h1 class="name">Derrick Adjie</h1>

    <div class="text-container2">
        <div class="row">
            <div class="col-sm-6">
                <p>
                <h3>Profile</h3>Detailed-orientated IT analyst and software developer, with the capabilities of
                being a fantastic asset to any business. I am looking for the opportunity to join a fantastic
                company as well as a strong team to continue developing and become a vital member. I have a fantastic
                business acumen and good programming skills.  I believe I have the competence and tenacity to grow as a
                person to help any organisation achieve their goal.<br/>

                <h3>Key Skills</h3>
                <p class="col-sm-6">
                    Django Framework   <br/>
                    Python, JavaScript & jQuery <br/>
                    HTML5 & CSS3<br/>
                    GitHub version control<br/>
                    Bootstrap & various web frameworks <br/>
                    Relational Databases & MySql <br/>
                </p>
                <p class="col-sm-6">
                    1st Line & 2nd Line support   <br/>
                    Software testing & Data Migration <br/>
                    Business use case development<br/>
                    Active Directory <br/>
                    Windows SQL Server 2008&2012 <br/>
                    Project Management <br/>
                </p>

                <p>
                <h3>Education</h3>
                <b><h4>De Montfort University, Leicester | BSc Computer Science | 2nd Class Honours</h4></b><br/>
                •	Researched, planned and designed a Fantasy Football Gaming Website.<br/>
                •	Managed deadlines and liaised with project leader/co-ordinator.<br/>
                •	Developed analytical and research skills, as well as understanding software methodologies.<br/>
                •	Enhanced my knowledge of various programming languages such as PHP, JAVA and C++.<br/>
                </p>



                </p>
            </div>
            <div class="col-sm-6">
                <h3>Work Experience</h3>
                <p>
                    London Borough of Camden                 2015-present<br/>

                    <b>Junior Business IT Analyst (IT Entrant)</b><br/>
                    •	Designed, implemented and supported full Online Training course for the business social care application Frameworki.
                    This allowed the business to increase funds, by reducing the amount used for classroom training.<br/>
                    •	Created and Implemented JavaScript code to allow for data to migrate to a new server.<br/>
                    •	Analysing current and designing new business processes using business models such as flowcharts and use case diagrams.<br/>
                    •	Apart of the team involved in full testing of multiple applications. This involved Test Strategy, Testing Plan, Test Cases,
                    Test Data and Test Environment. Without thorough testing, multiple applications would be unable to go live.<br/>
                    •	Master Data Management. Creating SQL scripts allowing the business to improve data analysis.<br/>
                    •	Using Business Objects to creating comprehensive reports, providing data to the business whilst making key decisions.<br/>
                    •	1st and 2nd line application support.<br/>
                </p>

                <p>
                    Freelancing                                2015-present<br/>

                    <b>Software Development</b><br/>
                    •	Created and designed a personal website using Django web framework. Source code has been published on GitHub.<br/>
                    •	Confident with Using the Django framework. Created small projects using Django<br/>
                    •	Confident using Python, HTML5, CSS3, JavaScript & jQuery as well as various other programming languages. Also comfortable working within the Linux environment.<br/>
                    •	Version control using Git and the GitHub repository.<br/>
                </p>
            </div>
        </div>
    </div>




{% endblock %}